# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaTest', '0002_auto_20161215_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.FileField(upload_to=b''),
        ),
    ]
