# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaTest', '0007_auto_20161219_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(default='images/None/No-img.jpg', upload_to='images/'),
        ),
    ]
