# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-16 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20161216_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(upload_to='car'),
        ),
    ]
