# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-16 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20161216_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
