# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20161216_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photo',
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='images/None/No-img.jpg', upload_to='images/'),
        ),
    ]
